name: Build Portable Tauri App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: install Rust stable
      uses: dtolnay/rust-toolchain@stable
      
    - name: Install dependencies
      run: npm install
      
    - name: Build Tauri App
      run: npm run tauri build -- --target x86_64-pc-windows-msvc
      
    - name: Upload Portable Executable
      uses: actions/upload-artifact@v4
      with:
        name: YTF-Portable-Windows
        path: src-tauri/target/x86_64-pc-windows-msvc/release/ytf.exe
